import {
  Body,
  Controller,
  Get,
  HttpCode,
  Param,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import { UserRole } from '@prisma/client';
import { EmailDraftRequestDto, EmailDraftRequestSchema } from '@amass/shared';
import { JwtAuthGuard } from '../auth/jwt.guard';
import { CedarGuard } from '../access-control/cedar.guard';
import { RequireCedar } from '../access-control/cedar.decorator';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { ZodValidationPipe } from '../../common/pipes/zod-validation.pipe';
import { SearchService, EntityType } from './search.service';
import { EmbeddingService } from './embedding.service';
import { DealAiService } from './deal-ai.service';
import { EnrichmentService } from './enrichment.service';
import { BriefService } from './brief.service';
import { EmailDraftService } from './email-draft.service';
import { IntentService } from './intent.service';

@Controller('ai')
@UseGuards(JwtAuthGuard, RolesGuard, CedarGuard)
export class AiController {
  constructor(
    private readonly search: SearchService,
    private readonly embedding: EmbeddingService,
    private readonly dealAi: DealAiService,
    private readonly enrichment: EnrichmentService,
    private readonly brief: BriefService,
    private readonly emailDraft: EmailDraftService,
    private readonly intent: IntentService,
  ) {}

  /**
   * GET /ai/search?q=acme&limit=10
   * Semantic search across companies + contacts + clients.
   */
  @Get('search')
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT, UserRole.VIEWER)
  async semanticSearch(
    @Query('q') q: string,
    @Query('limit') limit?: string,
  ) {
    if (!q?.trim()) return { results: [] };
    const results = await this.search.semanticSearch(q.trim(), parseLimit(limit, 10, 100));
    return { results };
  }

  /**
   * GET /ai/similar/:type/:id?limit=5
   * Find records similar to the given entity.
   * type: company | contact | client
   */
  @Get('similar/:type/:id')
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT, UserRole.VIEWER)
  async findSimilar(
    @Param('type') type: string,
    @Param('id') id: string,
    @Query('limit') limit?: string,
  ) {
    const results = await this.search.findSimilar(type as EntityType, id, parseLimit(limit, 5, 50));
    return { results };
  }

  /**
   * POST /ai/deals/:id/suggest
   * Get Claude's recommended next action for a deal.
   */
  @Post('deals/:id/suggest')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT)
  @RequireCedar({
    action: 'ai::deal-suggest',
    resource: (req) => `Deal::${(req as { params: { id: string } }).params.id}`,
  })
  async suggestDealAction(@Param('id') id: string) {
    return this.dealAi.suggest(id);
  }

  /**
   * POST /ai/reindex
   * Re-generate embeddings for all records in this tenant.
   * Restricted to OWNER/ADMIN. Can take a while if many records.
   */
  @Post('reindex')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN)
  @RequireCedar({ action: 'ai::reindex', resource: 'Embedding::*' })
  async reindex() {
    const counts = await this.embedding.reindexAll();
    return { message: 'Reindex complete', counts };
  }

  /** POST /ai/companies/:id/enrich — AI-powered company enrichment */
  @Post('companies/:id/enrich')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER)
  @RequireCedar({
    action: 'ai::enrich',
    resource: (req) => `Company::${(req as { params: { id: string } }).params.id}`,
  })
  enrichCompany(@Param('id') id: string) {
    return this.enrichment.enrichCompany(id);
  }

  /** POST /ai/contacts/:id/enrich — AI-powered contact enrichment */
  @Post('contacts/:id/enrich')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER)
  @RequireCedar({
    action: 'ai::enrich',
    resource: (req) => `Contact::${(req as { params: { id: string } }).params.id}`,
  })
  enrichContact(@Param('id') id: string) {
    return this.enrichment.enrichContact(id);
  }

  /**
   * GET /ai/brief?fresh=1
   *
   * AI Morning Brief for the dashboard hero. Per-user/tenant Romanian
   * summary + 3 priority actions, generated by Gemini/Claude with a
   * deterministic static fallback. Cached in Redis for 30 minutes.
   * Pass `?fresh=1` to bypass the cache.
   */
  @Get('brief')
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT, UserRole.VIEWER)
  getBrief(@Query('fresh') fresh?: string) {
    return this.brief.getBrief({ fresh: fresh === '1' || fresh === 'true' });
  }

  /**
   * POST /ai/email/draft
   * Generate a Romanian email draft for a contact based on a free-form
   * intent ("relance after demo", "thank for meeting"). Cedar guards
   * the contact resource because the email leaks contact context.
   */
  @Post('email/draft')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT)
  @RequireCedar({
    action: 'ai::email-draft',
    resource: (req) =>
      `Contact::${(req as { body: { contactId: string } }).body.contactId}`,
  })
  draftEmail(@Body(new ZodValidationPipe(EmailDraftRequestSchema)) dto: EmailDraftRequestDto) {
    return this.emailDraft.draft(dto.contactId, dto.intent, dto.tone);
  }

  /**
   * POST /ai/intent  { input: "creează deal pentru Acme" }
   * Parses a natural-language CRM command into a structured action.
   * Used by the Cmd-K "Acțiuni AI" section. No Cedar — the parsed action
   * runs through the FE which then calls the appropriate guarded route.
   */
  @Post('intent')
  @HttpCode(200)
  @Roles(UserRole.OWNER, UserRole.ADMIN, UserRole.MANAGER, UserRole.AGENT, UserRole.VIEWER)
  parseIntent(@Body() dto: { input?: string }) {
    return this.intent.parse(dto.input ?? '');
  }
}

/**
 * Coerce a `?limit=…` query param to a positive integer with bounds.
 * `parseInt('abc', 10)` returns NaN; passing NaN downstream lands in a
 * Prisma `take: NaN` which throws PrismaClientValidationError. Fail-soft
 * to the default + cap at the upper bound so a malicious caller can't
 * ask for `?limit=999999`.
 */
function parseLimit(raw: string | undefined, defaultValue: number, max: number): number {
  if (!raw) return defaultValue;
  const n = parseInt(raw, 10);
  if (Number.isNaN(n) || n <= 0) return defaultValue;
  return Math.min(n, max);
}
