/**
 * BriefService — AI Morning Brief for the dashboard hero strip.
 *
 * Returns a 2-3 sentence Romanian summary plus 3 priority items the
 * salesperson should focus on today, generated by Gemini (free tier
 * preferred) or Claude (paid fallback).
 *
 * Context sources (per-tenant, scoped via runWithTenant + RLS):
 *   - Overdue tasks assigned to this user (status = OPEN, dueAt < now)
 *   - Tasks due today
 *   - Reminders firing in the next 24h for this user
 *   - Open deals with `expectedCloseAt` in the next 7 days
 *   - Won/lost deals in the last 24h (momentum)
 *   - Calls completed in the last 24h
 *
 * Caching: Redis key `brief:{tenantId}:{userId}` with 30-minute TTL.
 * Manual `?fresh=1` bypasses the cache (still rewrites it). The cache is
 * invalidated naturally on TTL expiry; we don't proactively bust it on
 * data writes — the brief is meant to be a low-frequency morning read.
 *
 * Static fallback when no AI key is configured: a deterministic summary
 * built from the same context numbers, so the dashboard always renders
 * something useful even on free deployments.
 */
import { Injectable, Logger } from '@nestjs/common';
import Anthropic from '@anthropic-ai/sdk';
import { GoogleGenAI } from '@google/genai';

import { loadEnv } from '../../config/env';
import { PrismaService } from '../../infra/prisma/prisma.service';
import { RedisService } from '../../infra/redis/redis.service';
import { requireTenantContext } from '../../infra/prisma/tenant-context';
import { getBreaker } from '../../common/resilience/circuit-breaker';

export interface BriefPriority {
  /** Short imperative — "Sună Acme SRL", "Trimite oferta către X". */
  action: string;
  /** Optional 1-line context (deal title, deadline, etc.). */
  context?: string;
  /** Lucide-friendly visual hint, defaulted to "TASK". */
  icon: 'TASK' | 'CALL' | 'EMAIL' | 'DEAL' | 'REMINDER';
}

export interface MorningBrief {
  summary: string;
  priorities: BriefPriority[];
  generatedAt: string;
  /** True when the response came from cache. */
  cached: boolean;
  /** "ai" or "static" — useful for the FE to dim the AI sparkle when static. */
  source: 'ai' | 'static';
}

interface BriefContext {
  user: { fullName: string | null; email: string | null };
  overdueTasks: { title: string; dueAt: Date | null; priority: string; dealTitle: string | null }[];
  todayTasks: { title: string; dueAt: Date | null; priority: string }[];
  upcomingReminders: { title: string; remindAt: Date }[];
  closingDeals: {
    title: string;
    value: string | null;
    currency: string;
    expectedCloseAt: Date | null;
    companyName: string | null;
  }[];
  recentWins: number;
  recentLosses: number;
  callsLast24h: number;
}

type Provider = 'gemini' | 'anthropic' | 'none';

const SYSTEM_PROMPT = `You are a CRM morning-brief assistant for a Romanian B2B sales team. Given a JSON snapshot of the user's day, write a 2-3 sentence summary in **Romanian** (politicos, la persoana a-2-a, ton confident) and pick exactly 3 priority actions.

Respond ONLY with valid JSON (no markdown, no commentary) in this exact shape:
{
  "summary": "<2-3 propoziții, ~40-70 cuvinte total>",
  "priorities": [
    { "action": "<imperativ scurt, max 70 chars>", "context": "<opțional, 1 linie scurtă>", "icon": "TASK" | "CALL" | "EMAIL" | "DEAL" | "REMINDER" }
  ]
}`;

@Injectable()
export class BriefService {
  private readonly logger = new Logger(BriefService.name);
  private readonly anthropic: Anthropic | null;
  private readonly gemini: GoogleGenAI | null;
  private readonly provider: Provider;
  private static readonly CACHE_TTL_SEC = 30 * 60; // 30 minutes

  constructor(
    private readonly prisma: PrismaService,
    private readonly redis: RedisService,
  ) {
    const { GEMINI_API_KEY, ANTHROPIC_API_KEY } = loadEnv();
    this.gemini = GEMINI_API_KEY ? new GoogleGenAI({ apiKey: GEMINI_API_KEY }) : null;
    this.anthropic = ANTHROPIC_API_KEY
      ? new Anthropic({ apiKey: ANTHROPIC_API_KEY, timeout: 60_000, maxRetries: 1 })
      : null;
    if (this.gemini) this.provider = 'gemini';
    else if (this.anthropic) this.provider = 'anthropic';
    else this.provider = 'none';
  }

  async getBrief(opts: { fresh?: boolean } = {}): Promise<MorningBrief> {
    const { tenantId, userId } = requireTenantContext();
    if (!userId) {
      // /ai/brief is user-scoped — without a userId we'd cache cross-user.
      return this.staticFallback(await this.buildContext(tenantId, null));
    }

    const cacheKey = `brief:${tenantId}:${userId}`;
    if (!opts.fresh) {
      const cached = await this.redis.client.get(cacheKey);
      if (cached) {
        try {
          const parsed = JSON.parse(cached) as MorningBrief;
          return { ...parsed, cached: true };
        } catch {
          // Drop corrupt cache entry and recompute.
          await this.redis.client.del(cacheKey);
        }
      }
    }

    const ctx = await this.buildContext(tenantId, userId);
    const brief =
      this.provider === 'none' ? this.staticFallback(ctx) : await this.askLLM(ctx);

    await this.redis.client.set(cacheKey, JSON.stringify(brief), 'EX', BriefService.CACHE_TTL_SEC);
    return brief;
  }

  private async buildContext(tenantId: string, userId: string | null): Promise<BriefContext> {
    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const endOfToday = new Date(startOfToday.getTime() + 24 * 3600 * 1000);
    const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000);
    const last24h = new Date(now.getTime() - 24 * 3600 * 1000);

    return this.prisma.runWithTenant(tenantId, 'ro', async (tx) => {
      const user = userId
        ? await tx.user.findFirst({
            where: { id: userId },
            select: { fullName: true, email: true },
          })
        : null;

      const [overdueTasks, todayTasks, upcomingReminders, closingDeals, recentWins, recentLosses, callsLast24h] =
        await Promise.all([
          tx.task.findMany({
            where: {
              status: 'OPEN',
              deletedAt: null,
              dueAt: { lt: startOfToday },
              ...(userId ? { assigneeId: userId } : {}),
            },
            select: {
              title: true,
              dueAt: true,
              priority: true,
              deal: { select: { title: true } },
            },
            orderBy: { dueAt: 'asc' },
            take: 5,
          }),
          tx.task.findMany({
            where: {
              status: 'OPEN',
              deletedAt: null,
              dueAt: { gte: startOfToday, lt: endOfToday },
              ...(userId ? { assigneeId: userId } : {}),
            },
            select: { title: true, dueAt: true, priority: true },
            orderBy: { dueAt: 'asc' },
            take: 5,
          }),
          tx.reminder.findMany({
            where: {
              status: 'PENDING',
              remindAt: { gte: now, lt: endOfToday },
              ...(userId ? { actorId: userId } : {}),
            },
            select: { title: true, remindAt: true },
            orderBy: { remindAt: 'asc' },
            take: 5,
          }),
          tx.deal.findMany({
            where: {
              status: 'OPEN',
              deletedAt: null,
              expectedCloseAt: { gte: now, lt: in7Days },
              ...(userId ? { ownerId: userId } : {}),
            },
            select: {
              title: true,
              value: true,
              currency: true,
              expectedCloseAt: true,
              companyId: true,
            },
            orderBy: { expectedCloseAt: 'asc' },
            take: 5,
          }),
          tx.deal.count({
            where: {
              status: 'WON',
              closedAt: { gte: last24h },
              ...(userId ? { ownerId: userId } : {}),
            },
          }),
          tx.deal.count({
            where: {
              status: 'LOST',
              closedAt: { gte: last24h },
              ...(userId ? { ownerId: userId } : {}),
            },
          }),
          tx.call.count({
            where: {
              status: 'COMPLETED',
              endedAt: { gte: last24h },
              ...(userId ? { userId } : {}),
            },
          }),
        ]);

      // Resolve company names for the closing deals in a single follow-up query
      // (Deal has no `company` relation declared in the schema, only companyId).
      const companyIds = closingDeals
        .map((d) => d.companyId)
        .filter((id): id is string => Boolean(id));
      const companies = companyIds.length
        ? await tx.company.findMany({
            where: { id: { in: companyIds } },
            select: { id: true, name: true },
          })
        : [];
      const companyName = new Map(companies.map((c) => [c.id, c.name]));

      return {
        user: user
          ? { fullName: user.fullName ?? null, email: user.email ?? null }
          : { fullName: null, email: null },
        overdueTasks: overdueTasks.map((t) => ({
          title: t.title,
          dueAt: t.dueAt,
          priority: t.priority,
          dealTitle: t.deal?.title ?? null,
        })),
        todayTasks: todayTasks.map((t) => ({
          title: t.title,
          dueAt: t.dueAt,
          priority: t.priority,
        })),
        upcomingReminders: upcomingReminders.map((r) => ({ title: r.title, remindAt: r.remindAt })),
        closingDeals: closingDeals.map((d) => ({
          title: d.title,
          value: d.value?.toString() ?? null,
          currency: d.currency,
          expectedCloseAt: d.expectedCloseAt,
          companyName: d.companyId ? companyName.get(d.companyId) ?? null : null,
        })),
        recentWins,
        recentLosses,
        callsLast24h,
      };
    });
  }

  // ── AI path ────────────────────────────────────────────────────────────

  private async askLLM(ctx: BriefContext): Promise<MorningBrief> {
    const payload = JSON.stringify({
      user: ctx.user.fullName ?? ctx.user.email ?? 'utilizator',
      overdueTasks: ctx.overdueTasks.map((t) => ({
        title: t.title,
        dueAt: t.dueAt?.toISOString().slice(0, 10) ?? null,
        priority: t.priority,
        deal: t.dealTitle,
      })),
      todayTasks: ctx.todayTasks.map((t) => ({
        title: t.title,
        priority: t.priority,
      })),
      upcomingReminders: ctx.upcomingReminders.map((r) => ({
        title: r.title,
        in: minutesUntil(r.remindAt),
      })),
      closingDeals: ctx.closingDeals.map((d) => ({
        title: d.title,
        company: d.companyName,
        value: d.value,
        currency: d.currency,
        closesIn: d.expectedCloseAt ? daysUntil(d.expectedCloseAt) : null,
      })),
      recentWins: ctx.recentWins,
      recentLosses: ctx.recentLosses,
      callsLast24h: ctx.callsLast24h,
    });

    try {
      const text = await this.callLLM(payload);
      const parsed = JSON.parse(text) as {
        summary?: string;
        priorities?: BriefPriority[];
      };
      const priorities = (parsed.priorities ?? []).slice(0, 3).map((p) => ({
        action: typeof p.action === 'string' ? p.action.slice(0, 100) : 'Verifică pipeline-ul',
        context: typeof p.context === 'string' ? p.context.slice(0, 120) : undefined,
        icon: ['TASK', 'CALL', 'EMAIL', 'DEAL', 'REMINDER'].includes(p.icon)
          ? p.icon
          : ('TASK' as const),
      }));
      // Pad to 3 priorities so the FE layout is stable.
      while (priorities.length < 3) {
        priorities.push({ action: 'Revizuiește pipeline-ul curent', context: undefined, icon: 'DEAL' });
      }
      return {
        summary:
          (parsed.summary && parsed.summary.trim()) ||
          this.buildStaticSummary(ctx),
        priorities,
        generatedAt: new Date().toISOString(),
        cached: false,
        source: 'ai',
      };
    } catch (err) {
      this.logger.error('AI brief generation failed: %o', err);
      return this.staticFallback(ctx);
    }
  }

  private async callLLM(context: string): Promise<string> {
    if (this.provider === 'gemini' && this.gemini) {
      const res = await this.gemini.models.generateContent({
        model: 'gemini-2.0-flash',
        contents: context,
        config: {
          systemInstruction: SYSTEM_PROMPT,
          responseMimeType: 'application/json',
          maxOutputTokens: 384,
        },
      });
      return res.text ?? '{}';
    }
    if (this.provider === 'anthropic' && this.anthropic) {
      const anthropic = this.anthropic;
      const msg = await getBreaker('anthropic').exec(() =>
        anthropic.messages.create({
          model: 'claude-sonnet-4-6',
          max_tokens: 384,
          system: SYSTEM_PROMPT,
          messages: [{ role: 'user', content: context }],
        }),
      );
      return msg.content.find((b) => b.type === 'text')?.text ?? '{}';
    }
    return '{}';
  }

  // ── Static fallback (no API key OR LLM call failed) ────────────────────

  private staticFallback(ctx: BriefContext): MorningBrief {
    return {
      summary: this.buildStaticSummary(ctx),
      priorities: this.buildStaticPriorities(ctx),
      generatedAt: new Date().toISOString(),
      cached: false,
      source: 'static',
    };
  }

  private buildStaticSummary(ctx: BriefContext): string {
    const bits: string[] = [];
    if (ctx.overdueTasks.length > 0) {
      bits.push(`${ctx.overdueTasks.length} task-uri restante`);
    }
    if (ctx.todayTasks.length > 0) {
      bits.push(`${ctx.todayTasks.length} task-uri pentru azi`);
    }
    if (ctx.closingDeals.length > 0) {
      bits.push(`${ctx.closingDeals.length} deal-uri se închid în 7 zile`);
    }
    if (ctx.recentWins > 0) {
      bits.push(`${ctx.recentWins} câștiguri în ultimele 24h`);
    }

    if (bits.length === 0) {
      return 'Nicio urgență detectată. Profită de timpul liber pentru prospectare sau pentru a urmări lead-urile reci.';
    }
    return `Astăzi ai ${bits.slice(0, 3).join(', ')}. Concentrează-te pe ce contează acum.`;
  }

  private buildStaticPriorities(ctx: BriefContext): BriefPriority[] {
    const out: BriefPriority[] = [];
    if (ctx.overdueTasks[0]) {
      const t = ctx.overdueTasks[0];
      out.push({
        action: `Recuperează: ${t.title}`,
        context: t.dealTitle ? `Deal: ${t.dealTitle}` : undefined,
        icon: 'TASK',
      });
    }
    if (ctx.closingDeals[0]) {
      const d = ctx.closingDeals[0];
      out.push({
        action: `Urmărește: ${d.title}`,
        context: d.companyName
          ? `${d.companyName}${d.expectedCloseAt ? ` · închide ${d.expectedCloseAt.toISOString().slice(0, 10)}` : ''}`
          : undefined,
        icon: 'DEAL',
      });
    }
    if (ctx.upcomingReminders[0]) {
      const r = ctx.upcomingReminders[0];
      out.push({
        action: `Reminder: ${r.title}`,
        context: r.remindAt.toLocaleString('ro-RO'),
        icon: 'REMINDER',
      });
    }
    if (ctx.todayTasks[0] && out.length < 3) {
      out.push({
        action: `Astăzi: ${ctx.todayTasks[0].title}`,
        icon: 'TASK',
      });
    }
    while (out.length < 3) {
      out.push({ action: 'Revizuiește pipeline-ul curent', context: undefined, icon: 'DEAL' });
    }
    return out.slice(0, 3);
  }
}

function minutesUntil(date: Date): number {
  return Math.max(0, Math.round((date.getTime() - Date.now()) / 60000));
}

function daysUntil(date: Date): number {
  return Math.max(0, Math.round((date.getTime() - Date.now()) / (24 * 3600 * 1000)));
}
