#!/usr/bin/env bash
# Bootstrap AMASS-CRM pe un VPS Ubuntu curat.
#
# Un singur script = un singur server live. Roadmap:
#   1) instalează Docker + swap + firewall
#   2) clonează repo-ul (dacă nu deja clonat)
#   3) generează .env cu toate secretele random
#   4) actualizează Caddyfile cu domeniul tău
#   5) pornește întregul stack prin docker-compose
#   6) rulează migrațiile Prisma
#   7) creează primul tenant + owner

set -eu
# NOTE: we intentionally do NOT enable `pipefail` here — several common
# one-liners below (openssl | head -c N, tr -dc | head -c N) trigger
# SIGPIPE on the upstream command, which with pipefail silently aborts
# the script. Each individual command is checked by `set -e` already.

# Early banner so users see immediate feedback — previous versions exited
# silently at the password-gen pipeline before reaching any `log` line.
printf '\n\033[1;36m▶ bootstrap starting — installing Docker + deploying AMASS-CRM...\033[0m\n\n'

# ── Args ──────────────────────────────────────────────────────────────────
DOMAIN=""
OWNER_EMAIL=""
TENANT_SLUG="amass"
TENANT_NAME="Amass SRL"
OWNER_FULLNAME="Owner"
OWNER_PASSWORD=""

for arg in "$@"; do
  case $arg in
    --domain=*)       DOMAIN="${arg#*=}" ;;
    --email=*)        OWNER_EMAIL="${arg#*=}" ;;
    --tenant=*)       TENANT_SLUG="${arg#*=}" ;;
    --tenant-name=*)  TENANT_NAME="${arg#*=}" ;;
    --full-name=*)    OWNER_FULLNAME="${arg#*=}" ;;
    --password=*)     OWNER_PASSWORD="${arg#*=}" ;;
    *) echo "unknown arg: $arg" ; exit 1 ;;
  esac
done

if [[ -z "$DOMAIN" || -z "$OWNER_EMAIL" ]]; then
  cat <<EOF
Usage: $0 --domain=DOMAIN --email=EMAIL [--tenant=SLUG] [--tenant-name=NAME] [--full-name=NAME] [--password=PASS]

DOMAIN is the apex domain — the script will use crm.DOMAIN, api.crm.DOMAIN,
files.crm.DOMAIN. You MUST have A-records pointing all three at this VPS
BEFORE running this script, otherwise Caddy won't be able to obtain TLS certs.

If --password is omitted, a strong 24-char password is generated and printed
at the end.
EOF
  exit 1
fi

if [[ -z "$OWNER_PASSWORD" ]]; then
  # 24-char base64url string. Using openssl here (vs the older
  # `tr -dc < /dev/urandom | head -c 24` idiom) because that pipeline
  # SIGPIPEs `tr` when head closes early, which trips `set -o pipefail`
  # and kills the whole script.
  OWNER_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
  GENERATED_PASSWORD="yes"
else
  GENERATED_PASSWORD="no"
fi

REPO_URL="https://github.com/olteancristianradu/amass-crm-v2.git"
INSTALL_DIR="/opt/amass"

log()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (or via sudo)."

# ── 1. System deps ────────────────────────────────────────────────────────
log "Updating system + installing Docker"
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw jq openssl

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi

# Docker Compose v2 ships with docker. Sanity check.
docker compose version >/dev/null 2>&1 || die "docker compose v2 not found"

# ── 2. Swap (helps Whisper + Prisma generate on 4GB VPSes) ────────────────
if ! swapon --show | grep -q '/swapfile'; then
  log "Creating 4GB swap file"
  fallocate -l 4G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ── 3. Firewall ───────────────────────────────────────────────────────────
log "Configuring UFW (22/80/443 only)"
ufw allow 22/tcp >/dev/null || true
ufw allow 80/tcp >/dev/null || true
ufw allow 443/tcp >/dev/null || true
ufw --force enable >/dev/null

# ── 4. Clone repo ─────────────────────────────────────────────────────────
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
  log "Cloning repo to $INSTALL_DIR"
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
else
  log "Repo already present — pulling latest"
  git -C "$INSTALL_DIR" pull --ff-only
fi

cd "$INSTALL_DIR"

# ── 5. Generate .env if missing ───────────────────────────────────────────
if [[ ! -f .env ]]; then
  log "Generating .env with random secrets"

  hex() { openssl rand -hex 32; }
  # `cut -c1-N` instead of `head -c N` — head-c closes the pipe early and
  # SIGPIPEs the upstream openssl; cut reads the whole line first.
  b64() { openssl rand -base64 48 | tr -d '/+=' | cut -c1-"${1:-32}"; }

  JWT_SECRET=$(hex)
  JWT_REFRESH_SECRET=$(hex)
  ENCRYPTION_KEY=$(hex)
  AI_WORKER_SECRET=$(hex)
  METRICS_AUTH_TOKEN=$(hex)
  POSTGRES_PASSWORD=$(b64 24)
  MINIO_ROOT_PASSWORD=$(b64 24)
  MINIO_ACCESS_KEY=$(b64 20)
  MINIO_SECRET_KEY=$(b64 40)

  cat > .env <<EOF
# Auto-generated by bootstrap-vps.sh on $(date -u +%FT%TZ)
NODE_ENV=production
API_PORT=3000
WEB_PORT=80
AI_WORKER_PORT=8000

# ── Database ────────────────────────────────────────────────────────
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=amass_crm
POSTGRES_PORT=5432
DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@postgres:5432/amass_crm?schema=public

# ── Redis ───────────────────────────────────────────────────────────
REDIS_PORT=6379
REDIS_URL=redis://redis:6379

# ── MinIO (self-hosted S3) ──────────────────────────────────────────
MINIO_ROOT_USER=$MINIO_ACCESS_KEY
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_BUCKET=amass-files
MINIO_ENDPOINT=https://files.crm.$DOMAIN
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY

# ── Auth ────────────────────────────────────────────────────────────
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL_DAYS=30
ENCRYPTION_KEY=$ENCRYPTION_KEY

# ── Origins / public URLs ──────────────────────────────────────────
CORS_ALLOWED_ORIGINS=https://crm.$DOMAIN
PUBLIC_API_BASE_URL=https://api.crm.$DOMAIN

# ── Metrics (admin-only) ────────────────────────────────────────────
METRICS_AUTH_TOKEN=$METRICS_AUTH_TOKEN

# ── AI worker ───────────────────────────────────────────────────────
AI_WORKER_SECRET=$AI_WORKER_SECRET
AI_WORKER_URL=http://ai-worker:8000
WHISPER_MODEL=off
PRESIDIO_ENABLED=false

# ── Optional integrations (fill in later via docker compose restart) ─
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_WEBHOOK_BASE_URL=https://api.crm.$DOMAIN
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
GEMINI_API_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
SENTRY_DSN=
LOG_LEVEL=info
EOF

  chmod 600 .env
  log ".env written (mode 600)"
else
  log ".env already exists — leaving untouched"
fi

# ── 6. Caddyfile with real domain ─────────────────────────────────────────
CADDY_FILE="$INSTALL_DIR/infra/caddy/Caddyfile.prod"
if ! grep -q "crm.$DOMAIN " "$CADDY_FILE" 2>/dev/null; then
  log "Writing Caddyfile for crm.$DOMAIN"
  cat > "$CADDY_FILE" <<EOF
{
  email admin@$DOMAIN
  admin off
}

# Web SPA
crm.$DOMAIN {
  encode zstd gzip
  header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options    "nosniff"
    X-Frame-Options           "DENY"
    Referrer-Policy           "strict-origin-when-cross-origin"
    -Server
  }
  reverse_proxy web:80
}

# API
api.crm.$DOMAIN {
  encode zstd gzip
  request_body { max_size 25MB }
  header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options    "nosniff"
    -Server
  }
  reverse_proxy api:3000
}

# MinIO (presigned GET/PUT from the browser)
files.crm.$DOMAIN {
  encode zstd gzip
  request_body { max_size 500MB }
  reverse_proxy minio:9000
}
EOF
fi

# ── 7. Start the stack ────────────────────────────────────────────────────
log "docker compose up -d (this can take 5-10 minutes first time)"
docker compose -f infra/docker-compose.yml --env-file .env up -d --build

log "Waiting for postgres + api to become healthy (up to 90s)"
for i in $(seq 1 18); do
  if docker exec amass-postgres pg_isready -U postgres >/dev/null 2>&1; then
    break
  fi
  sleep 5
done

# ── 8. Prisma migrate ─────────────────────────────────────────────────────
log "Running prisma migrate deploy"
docker exec amass-api pnpm --filter @amass/api exec prisma migrate deploy \
  || warn "migrate deploy failed — check 'docker logs amass-api'"

# ── 9. Create first tenant + owner ────────────────────────────────────────
log "Registering first tenant + owner"
# Retry a few times while the API warms up.
for i in $(seq 1 10); do
  if curl -sSf -o /tmp/register.json -w '%{http_code}' \
    -X POST "http://localhost:3000/api/v1/auth/register" \
    -H 'content-type: application/json' \
    -d "$(jq -n --arg ts "$TENANT_SLUG" --arg tn "$TENANT_NAME" \
                --arg e "$OWNER_EMAIL" --arg p "$OWNER_PASSWORD" --arg fn "$OWNER_FULLNAME" \
                '{tenantSlug:$ts,tenantName:$tn,email:$e,password:$p,fullName:$fn}')" \
    | grep -q '20[01]'; then
    REGISTER_OK="yes"
    break
  fi
  sleep 6
done

# ── Summary ───────────────────────────────────────────────────────────────
echo
echo "=========================================================================="
echo "  AMASS-CRM is live 🚀"
echo "=========================================================================="
echo "  Web:     https://crm.$DOMAIN"
echo "  API:     https://api.crm.$DOMAIN/api/v1"
echo "  Files:   https://files.crm.$DOMAIN"
echo
echo "  Tenant:   $TENANT_SLUG  ($TENANT_NAME)"
echo "  Owner:    $OWNER_EMAIL"
if [[ "$GENERATED_PASSWORD" == "yes" ]]; then
  echo "  Password: $OWNER_PASSWORD   ← SAVE THIS NOW"
else
  echo "  Password: (the one you passed via --password)"
fi
echo
echo "  Secrets + DB password are in: $INSTALL_DIR/.env  (mode 600)"
echo
echo "  Next steps:"
echo "    - Open https://crm.$DOMAIN, log in with slug '$TENANT_SLUG'"
echo "    - To add Twilio/Stripe/Anthropic later: edit .env, then:"
echo "        cd $INSTALL_DIR && docker compose -f infra/docker-compose.yml restart api ai-worker"
echo "    - Backups: scripts in $INSTALL_DIR/infra/scripts/"
echo "=========================================================================="
